/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as MeetRoomIdRouteImport } from './routes/meet.$roomId'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedVacanciesIndexRouteImport } from './routes/_authenticated/vacancies.index'
import { Route as AuthenticatedInterviewsIndexRouteImport } from './routes/_authenticated/interviews.index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedVacanciesNewRouteImport } from './routes/_authenticated/vacancies.new'
import { Route as AuthenticatedVacanciesIdRouteImport } from './routes/_authenticated/vacancies.$id'
import { Route as AuthenticatedCandidatesNewRouteImport } from './routes/_authenticated/candidates.new'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiPublicHooksHrDailyDigestRouteImport } from './routes/api/public/hooks/hr-daily-digest'
import { Route as AuthenticatedVacanciesIdPipelineRouteImport } from './routes/_authenticated/vacancies.$id.pipeline'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoomIdRoute = MeetRoomIdRouteImport.update({
  id: '/meet/$roomId',
  path: '/meet/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVacanciesIndexRoute =
  AuthenticatedVacanciesIndexRouteImport.update({
    id: '/vacancies/',
    path: '/vacancies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewsIndexRoute =
  AuthenticatedInterviewsIndexRouteImport.update({
    id: '/interviews/',
    path: '/interviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVacanciesNewRoute =
  AuthenticatedVacanciesNewRouteImport.update({
    id: '/vacancies/new',
    path: '/vacancies/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVacanciesIdRoute =
  AuthenticatedVacanciesIdRouteImport.update({
    id: '/vacancies/$id',
    path: '/vacancies/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesNewRoute =
  AuthenticatedCandidatesNewRouteImport.update({
    id: '/candidates/new',
    path: '/candidates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksHrDailyDigestRoute =
  ApiPublicHooksHrDailyDigestRouteImport.update({
    id: '/api/public/hooks/hr-daily-digest',
    path: '/api/public/hooks/hr-daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVacanciesIdPipelineRoute =
  AuthenticatedVacanciesIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedVacanciesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/jobs/$id': typeof JobsIdRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/vacancies/$id': typeof AuthenticatedVacanciesIdRouteWithChildren
  '/vacancies/new': typeof AuthenticatedVacanciesNewRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/interviews/': typeof AuthenticatedInterviewsIndexRoute
  '/vacancies/': typeof AuthenticatedVacanciesIndexRoute
  '/vacancies/$id/pipeline': typeof AuthenticatedVacanciesIdPipelineRoute
  '/api/public/hooks/hr-daily-digest': typeof ApiPublicHooksHrDailyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/jobs/$id': typeof JobsIdRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/vacancies/$id': typeof AuthenticatedVacanciesIdRouteWithChildren
  '/vacancies/new': typeof AuthenticatedVacanciesNewRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/interviews': typeof AuthenticatedInterviewsIndexRoute
  '/vacancies': typeof AuthenticatedVacanciesIndexRoute
  '/vacancies/$id/pipeline': typeof AuthenticatedVacanciesIdPipelineRoute
  '/api/public/hooks/hr-daily-digest': typeof ApiPublicHooksHrDailyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/jobs/$id': typeof JobsIdRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/_authenticated/vacancies/$id': typeof AuthenticatedVacanciesIdRouteWithChildren
  '/_authenticated/vacancies/new': typeof AuthenticatedVacanciesNewRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/interviews/': typeof AuthenticatedInterviewsIndexRoute
  '/_authenticated/vacancies/': typeof AuthenticatedVacanciesIndexRoute
  '/_authenticated/vacancies/$id/pipeline': typeof AuthenticatedVacanciesIdPipelineRoute
  '/api/public/hooks/hr-daily-digest': typeof ApiPublicHooksHrDailyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/portal'
    | '/jobs/$id'
    | '/meet/$roomId'
    | '/jobs/'
    | '/admin/users'
    | '/candidates/$id'
    | '/candidates/new'
    | '/vacancies/$id'
    | '/vacancies/new'
    | '/candidates/'
    | '/interviews/'
    | '/vacancies/'
    | '/vacancies/$id/pipeline'
    | '/api/public/hooks/hr-daily-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/portal'
    | '/jobs/$id'
    | '/meet/$roomId'
    | '/jobs'
    | '/admin/users'
    | '/candidates/$id'
    | '/candidates/new'
    | '/vacancies/$id'
    | '/vacancies/new'
    | '/candidates'
    | '/interviews'
    | '/vacancies'
    | '/vacancies/$id/pipeline'
    | '/api/public/hooks/hr-daily-digest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/portal'
    | '/jobs/$id'
    | '/meet/$roomId'
    | '/jobs/'
    | '/_authenticated/admin/users'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/new'
    | '/_authenticated/vacancies/$id'
    | '/_authenticated/vacancies/new'
    | '/_authenticated/candidates/'
    | '/_authenticated/interviews/'
    | '/_authenticated/vacancies/'
    | '/_authenticated/vacancies/$id/pipeline'
    | '/api/public/hooks/hr-daily-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JobsIdRoute: typeof JobsIdRoute
  MeetRoomIdRoute: typeof MeetRoomIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiPublicHooksHrDailyDigestRoute: typeof ApiPublicHooksHrDailyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$roomId': {
      id: '/meet/$roomId'
      path: '/meet/$roomId'
      fullPath: '/meet/$roomId'
      preLoaderRoute: typeof MeetRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vacancies/': {
      id: '/_authenticated/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies/'
      preLoaderRoute: typeof AuthenticatedVacanciesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews/': {
      id: '/_authenticated/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AuthenticatedInterviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vacancies/new': {
      id: '/_authenticated/vacancies/new'
      path: '/vacancies/new'
      fullPath: '/vacancies/new'
      preLoaderRoute: typeof AuthenticatedVacanciesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vacancies/$id': {
      id: '/_authenticated/vacancies/$id'
      path: '/vacancies/$id'
      fullPath: '/vacancies/$id'
      preLoaderRoute: typeof AuthenticatedVacanciesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/new': {
      id: '/_authenticated/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AuthenticatedCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/hr-daily-digest': {
      id: '/api/public/hooks/hr-daily-digest'
      path: '/api/public/hooks/hr-daily-digest'
      fullPath: '/api/public/hooks/hr-daily-digest'
      preLoaderRoute: typeof ApiPublicHooksHrDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vacancies/$id/pipeline': {
      id: '/_authenticated/vacancies/$id/pipeline'
      path: '/pipeline'
      fullPath: '/vacancies/$id/pipeline'
      preLoaderRoute: typeof AuthenticatedVacanciesIdPipelineRouteImport
      parentRoute: typeof AuthenticatedVacanciesIdRoute
    }
  }
}

interface AuthenticatedVacanciesIdRouteChildren {
  AuthenticatedVacanciesIdPipelineRoute: typeof AuthenticatedVacanciesIdPipelineRoute
}

const AuthenticatedVacanciesIdRouteChildren: AuthenticatedVacanciesIdRouteChildren =
  {
    AuthenticatedVacanciesIdPipelineRoute:
      AuthenticatedVacanciesIdPipelineRoute,
  }

const AuthenticatedVacanciesIdRouteWithChildren =
  AuthenticatedVacanciesIdRoute._addFileChildren(
    AuthenticatedVacanciesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesNewRoute: typeof AuthenticatedCandidatesNewRoute
  AuthenticatedVacanciesIdRoute: typeof AuthenticatedVacanciesIdRouteWithChildren
  AuthenticatedVacanciesNewRoute: typeof AuthenticatedVacanciesNewRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
  AuthenticatedInterviewsIndexRoute: typeof AuthenticatedInterviewsIndexRoute
  AuthenticatedVacanciesIndexRoute: typeof AuthenticatedVacanciesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedCandidatesNewRoute: AuthenticatedCandidatesNewRoute,
  AuthenticatedVacanciesIdRoute: AuthenticatedVacanciesIdRouteWithChildren,
  AuthenticatedVacanciesNewRoute: AuthenticatedVacanciesNewRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  AuthenticatedInterviewsIndexRoute: AuthenticatedInterviewsIndexRoute,
  AuthenticatedVacanciesIndexRoute: AuthenticatedVacanciesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JobsIdRoute: JobsIdRoute,
  MeetRoomIdRoute: MeetRoomIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiPublicHooksHrDailyDigestRoute: ApiPublicHooksHrDailyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
